// @generated by protoc-gen-es v2.6.0 with parameter "target=ts"
// @generated from file execution.proto (package execution, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file execution.proto.
 */
export const file_execution: GenFile = /*@__PURE__*/
  fileDesc("Cg9leGVjdXRpb24ucHJvdG8SCWV4ZWN1dGlvbiIyChNFbnZpcm9ubWVudFZhcmlhYmxlEgwKBG5hbWUYASABKAkSDQoFdmFsdWUYAiABKAkiogEKGEV4ZWN1dGlvbkVudmlyb25tZW50U3BlYxI9ChVlbnZpcm9ubWVudF92YXJpYWJsZXMYASADKAsyHi5leGVjdXRpb24uRW52aXJvbm1lbnRWYXJpYWJsZRIcChRsYW5ndWFnZURlcGVuZGVuY2llcxgCIAMoCRIaChJzeXN0ZW1EZXBlbmRlbmNpZXMYAyADKAkSDQoFc2V0dXAYBCABKAki/QEKEEV4ZWN1dGlvblJlcXVlc3QSOAoLZW52aXJvbm1lbnQYASABKAsyIy5leGVjdXRpb24uRXhlY3V0aW9uRW52aXJvbm1lbnRTcGVjEgwKBGNvZGUYAiABKAkSEAoIbGFuZ3VhZ2UYAyABKAkSDwoHdmVyc2lvbhgEIAEoCRITCgttYXhfcmV0cmllcxgFIAEoBRIPCgd0aW1lb3V0GAYgASgFEhMKC2NtZExpbmVBcmdzGAcgASgJEhQKDGNvbXBpbGVyQXJncxgIIAEoCRIPCgdjb21tYW5kGAkgASgJEg0KBWZpbGVzGAogASgJEg0KBWlucHV0GAsgASgJIkUKEUV4ZWN1dGlvblJlc3BvbnNlEg0KBWpvYklkGAEgASgDEg4KBmV2ZW50cxgCIAEoCRIRCgl3ZWJzb2NrZXQYAyABKAkicwoSRXhlY3V0aW9uV1NNZXNzYWdlEg4KBnN0YXR1cxgBIAEoCRINCgVqb2JJZBgCIAEoBRIRCgRsb2dzGAMgASgJSACIAQESFQoIZXJyb3JNc2cYBCABKAlIAYgBAUIHCgVfbG9nc0ILCglfZXJyb3JNc2diBnByb3RvMw");

/**
 * @generated from message execution.EnvironmentVariable
 */
export type EnvironmentVariable = Message<"execution.EnvironmentVariable"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string value = 2;
   */
  value: string;
};

/**
 * Describes the message execution.EnvironmentVariable.
 * Use `create(EnvironmentVariableSchema)` to create a new message.
 */
export const EnvironmentVariableSchema: GenMessage<EnvironmentVariable> = /*@__PURE__*/
  messageDesc(file_execution, 0);

/**
 * @generated from message execution.ExecutionEnvironmentSpec
 */
export type ExecutionEnvironmentSpec = Message<"execution.ExecutionEnvironmentSpec"> & {
  /**
   * @generated from field: repeated execution.EnvironmentVariable environment_variables = 1;
   */
  environmentVariables: EnvironmentVariable[];

  /**
   * @generated from field: repeated string languageDependencies = 2;
   */
  languageDependencies: string[];

  /**
   * @generated from field: repeated string systemDependencies = 3;
   */
  systemDependencies: string[];

  /**
   * @generated from field: string setup = 4;
   */
  setup: string;
};

/**
 * Describes the message execution.ExecutionEnvironmentSpec.
 * Use `create(ExecutionEnvironmentSpecSchema)` to create a new message.
 */
export const ExecutionEnvironmentSpecSchema: GenMessage<ExecutionEnvironmentSpec> = /*@__PURE__*/
  messageDesc(file_execution, 1);

/**
 * @generated from message execution.ExecutionRequest
 */
export type ExecutionRequest = Message<"execution.ExecutionRequest"> & {
  /**
   * @generated from field: execution.ExecutionEnvironmentSpec environment = 1;
   */
  environment?: ExecutionEnvironmentSpec;

  /**
   * @generated from field: string code = 2;
   */
  code: string;

  /**
   * @generated from field: string language = 3;
   */
  language: string;

  /**
   * @generated from field: string version = 4;
   */
  version: string;

  /**
   * @generated from field: int32 max_retries = 5;
   */
  maxRetries: number;

  /**
   * @generated from field: int32 timeout = 6;
   */
  timeout: number;

  /**
   * @generated from field: string cmdLineArgs = 7;
   */
  cmdLineArgs: string;

  /**
   * @generated from field: string compilerArgs = 8;
   */
  compilerArgs: string;

  /**
   * @generated from field: string command = 9;
   */
  command: string;

  /**
   * @generated from field: string files = 10;
   */
  files: string;

  /**
   * @generated from field: string input = 11;
   */
  input: string;
};

/**
 * Describes the message execution.ExecutionRequest.
 * Use `create(ExecutionRequestSchema)` to create a new message.
 */
export const ExecutionRequestSchema: GenMessage<ExecutionRequest> = /*@__PURE__*/
  messageDesc(file_execution, 2);

/**
 * @generated from message execution.ExecutionResponse
 */
export type ExecutionResponse = Message<"execution.ExecutionResponse"> & {
  /**
   * @generated from field: int64 jobId = 1;
   */
  jobId: bigint;

  /**
   * @generated from field: string events = 2;
   */
  events: string;

  /**
   * @generated from field: string websocket = 3;
   */
  websocket: string;
};

/**
 * Describes the message execution.ExecutionResponse.
 * Use `create(ExecutionResponseSchema)` to create a new message.
 */
export const ExecutionResponseSchema: GenMessage<ExecutionResponse> = /*@__PURE__*/
  messageDesc(file_execution, 3);

/**
 * @generated from message execution.ExecutionWSMessage
 */
export type ExecutionWSMessage = Message<"execution.ExecutionWSMessage"> & {
  /**
   * @generated from field: string status = 1;
   */
  status: string;

  /**
   * @generated from field: int32 jobId = 2;
   */
  jobId: number;

  /**
   * @generated from field: optional string logs = 3;
   */
  logs?: string;

  /**
   * @generated from field: optional string errorMsg = 4;
   */
  errorMsg?: string;
};

/**
 * Describes the message execution.ExecutionWSMessage.
 * Use `create(ExecutionWSMessageSchema)` to create a new message.
 */
export const ExecutionWSMessageSchema: GenMessage<ExecutionWSMessage> = /*@__PURE__*/
  messageDesc(file_execution, 4);

